### ISSUE TITLE
Pending checklist courier

### ISSUE THREAD

**Issue by danielfbl** [appjusto/app#12]
- [x] add back the "Fleet" item. For now, the "advance" button will not need fleet information;

- [x] fix the "steps counter" for the image files;
-> it only works when you reload the PendingChecklist screen. It should also work when you navigate back the first time when the user submits his images.

- [x] review the "checked" icon display. It should appear to the left of the title and above the subtitle (check figma)

- [x] store the docs verification so it won't happen again when you return to the pending checklist screen; 
maybe an useMemo to store all the values we need in this screen

- [x] require fleet info to advance and add the checked icon when done

### Photos

- [x] make the "squares" clickable just as the configitems; 

- [x] take a look at the layout/distance between elements in the screen

- [x] show activity indicator in the button

**Comment by pdandradeb** [comment]
- [ ] When returning to the checklist after adding the photos the check on photos wasn't updated
