### ISSUE TITLE
Pre-deployment checklist

### ISSUE THREAD

**Issue by pdandradeb** [appjusto/app#22]
- [x] Require only necessary permissions at app.json
```
"permissions": [
  "ACCESS_COARSE_LOCATION",
  "ACCESS_FINE_LOCATION",
  "CAMERA",
  "READ_EXTERNAL_STORAGE",
  "WRITE_EXTERNAL_STORAGE",
  "NOTIFICATIONS"
],

```

- [x] Configure /.well-known/apple-app-site-association to handle iOS deeplinks individually
- [x] Complete #7 
- [x] Update `validateProfile` to reject courier's profile when necessary
- [x] Create new firebase project for production environment
- [x] Remove `test` flag from `common/store/api/payment/iugu.createPaymentToken`
- [x] Set firestore initial dataset
- [x] Increase `fetchFleets` query limit
- [x] Conform to [privacy requirements](https://developer.apple.com/app-store/app-privacy-details/)
---

Permissions documentation:

https://docs.expo.io/versions/latest/sdk/permissions/
https://docs.expo.io/versions/latest/config/app/#permissions
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW1
